---
:project:
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: yes

:release_build:
  :output: pf_gtk

:module_generator:
  :source_root: source
  :test_root: tests

:paths:
  :test:
    - tests/**
    - vendor/bstring/
  :source:
    - source/**
    - vendor/bstring/

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :includes:
    - types.h
  :treat_as:
    UINT: INT
    Status_T: INT

:plugins:
  :load_paths:
    - "#{File.join(PROJECT_CEEDLING_ROOT, 'plugins')}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator

:tools:
  :test_compiler: &compiler_argz
    :executable: gcc
    :arguments:
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - "#{`pkg-config --cflags gtk+-2.0`}"
      - "#{`pkg-config --cflags libpcre`}"
      - -c ${1} 
      - -o ${2} 
  :test_linker: &linker_argz
    :executable: gcc
    :arguments: 
      - "#{`pkg-config --libs gtk+-2.0`}"
      - "#{`pkg-config --libs libpcre`}"
      - ${1}
      - -o ${2} 
  :release_compiler: *compiler_argz
  :release_linker: *linker_argz
...
